# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'burnettk/vim-angular'

[[plugins]]
repo = 'othree/yajs'
